numactl --membind=0 /home/wjxt/gxr/testMongoDB/build//run_clients --num_threads=40 --core_binding=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63 --str_key_size=8 --str_value_size=100 --URI_set=mongodb://172.20.208.111:27017,mongodb://172.20.208.111:27018,mongodb://172.20.208.111:27019,mongodb://172.20.208.111:27020,mongodb://172.20.208.111:27021,mongodb://172.20.208.111:27022,mongodb://172.20.208.111:27023,mongodb://172.20.208.111:27024,mongodb://172.20.208.111:27025,mongodb://172.20.208.111:27026,mongodb://172.20.208.111:27027,mongodb://172.20.208.111:27028,mongodb://172.20.208.111:27029,mongodb://172.20.208.111:27030,mongodb://172.20.208.111:27031,mongodb://172.20.208.111:27032,mongodb://172.20.208.111:27033,mongodb://172.20.208.111:27034,mongodb://172.20.208.111:27035,mongodb://172.20.208.111:27036,mongodb://172.20.208.111:27037,mongodb://172.20.208.111:27038,mongodb://172.20.208.111:27039,mongodb://172.20.208.111:27040,mongodb://172.20.208.111:27041,mongodb://172.20.208.111:27042,mongodb://172.20.208.111:27043,mongodb://172.20.208.111:27044,mongodb://172.20.208.111:27045,mongodb://172.20.208.111:27046,mongodb://172.20.208.111:27047,mongodb://172.20.208.111:27048,mongodb://172.20.208.111:27049,mongodb://172.20.208.111:27050,mongodb://172.20.208.111:27051,mongodb://172.20.208.111:27052,mongodb://172.20.208.111:27053,mongodb://172.20.208.111:27054,mongodb://172.20.208.111:27055,mongodb://172.20.208.111:27056,mongodb://172.20.208.111:27057,mongodb://172.20.208.111:27058,mongodb://172.20.208.111:27059,mongodb://172.20.208.111:27060,mongodb://172.20.208.111:27061,mongodb://172.20.208.111:27062,mongodb://172.20.208.111:27063,mongodb://172.20.208.111:27064 --URI=mongodb://172.20.208.111:27017 --time_interval=10 --first_mode=false
terminate called after throwing an instance of 'mongocxx::v_noabi::bulk_write_exception'
  what():  Failed to send "insert" command with database "mydb_11": Failure during socket delivery: Connection reset by peer (0): generic server error
timeout: the monitored command dumped core
